/* ============ 英语积累数据（奶豆加油站）============
 * EN_WORDS:  单词，grade 1=一年级 … 6=六年级 7=初一 8=初二 9=初三
 *            se=简单例句 sz=例句中文
 * EN_PHRASES:常用短句，grade 1-6 小学必会句子
 * EN_PHONICS:自然拼读，s=音标 sp=发音提示 ex=[{w:单词,ph:音标}]
 */
var EN_WORDS = [
/* ---- 一年级（文具·数字·颜色·身体·动物）---- */
{en:"pen",ph:"/pen/",zh:"钢笔",e:"🖊️",g:1,se:"I have a pen.",sz:"我有一支钢笔。"},
{en:"pencil",ph:"/ˈpen.səl/",zh:"铅笔",e:"✏️",g:1,se:"This is a pencil.",sz:"这是一支铅笔。"},
{en:"ruler",ph:"/ˈruː.lər/",zh:"尺子",e:"📏",g:1,se:"My ruler is long.",sz:"我的尺子很长。"},
{en:"eraser",ph:"/ɪˈreɪ.zər/",zh:"橡皮",e:"🧽",g:1,se:"I have an eraser.",sz:"我有一块橡皮。"},
{en:"bag",ph:"/bæɡ/",zh:"书包",e:"🎒",g:1,se:"My bag is blue.",sz:"我的书包是蓝色的。"},
{en:"book",ph:"/bʊk/",zh:"书",e:"📖",g:1,se:"Open your book.",sz:"打开你的书。"},
{en:"school",ph:"/skuːl/",zh:"学校",e:"🏫",g:1,se:"I go to school.",sz:"我去上学。"},
{en:"desk",ph:"/desk/",zh:"书桌",e:"🪑",g:1,se:"The book is on the desk.",sz:"书在书桌上。"},
{en:"chair",ph:"/tʃeər/",zh:"椅子",e:"🪑",g:1,se:"Sit on the chair.",sz:"坐在椅子上。"},
{en:"crayon",ph:"/ˈkreɪ.ɒn/",zh:"蜡笔",e:"🖍️",g:1,se:"I color with a crayon.",sz:"我用蜡笔画画。"},
{en:"one",ph:"/wʌn/",zh:"一",e:"1️⃣",g:1,se:"I have one apple.",sz:"我有一个苹果。"},
{en:"two",ph:"/tuː/",zh:"二",e:"2️⃣",g:1,se:"I see two cats.",sz:"我看见两只猫。"},
{en:"three",ph:"/θriː/",zh:"三",e:"3️⃣",g:1,se:"I am three years old.",sz:"我三岁。"},
{en:"four",ph:"/fɔː/",zh:"四",e:"4️⃣",g:1,se:"Four birds fly.",sz:"四只鸟在飞。"},
{en:"five",ph:"/faɪv/",zh:"五",e:"5️⃣",g:1,se:"I have five fingers.",sz:"我有五个手指。"},
{en:"six",ph:"/sɪks/",zh:"六",e:"6️⃣",g:1,se:"Six ducks swim.",sz:"六只鸭子在游泳。"},
{en:"seven",ph:"/ˈsev.ən/",zh:"七",e:"7️⃣",g:1,se:"Seven stars shine.",sz:"七颗星星在闪烁。"},
{en:"eight",ph:"/eɪt/",zh:"八",e:"8️⃣",g:1,se:"I am eight.",sz:"我八岁。"},
{en:"nine",ph:"/naɪn/",zh:"九",e:"9️⃣",g:1,se:"Nine fish swim.",sz:"九条鱼在游。"},
{en:"ten",ph:"/ten/",zh:"十",e:"🔟",g:1,se:"I have ten fingers.",sz:"我有十个手指。"},
{en:"red",ph:"/red/",zh:"红色",e:"🔴",g:1,se:"The apple is red.",sz:"苹果是红色的。"},
{en:"blue",ph:"/bluː/",zh:"蓝色",e:"🔵",g:1,se:"The sky is blue.",sz:"天空是蓝色的。"},
{en:"green",ph:"/ɡriːn/",zh:"绿色",e:"🟢",g:1,se:"The grass is green.",sz:"草是绿色的。"},
{en:"yellow",ph:"/ˈjel.əʊ/",zh:"黄色",e:"🟡",g:1,se:"The sun is yellow.",sz:"太阳是黄色的。"},
{en:"black",ph:"/blæk/",zh:"黑色",e:"⚫",g:1,se:"The cat is black.",sz:"猫是黑色的。"},
{en:"white",ph:"/waɪt/",zh:"白色",e:"⚪",g:1,se:"The snow is white.",sz:"雪是白色的。"},
{en:"pink",ph:"/pɪŋk/",zh:"粉色",e:"🌸",g:1,se:"I like pink.",sz:"我喜欢粉色。"},
{en:"head",ph:"/hed/",zh:"头",e:"🙆",g:1,se:"Touch your head.",sz:"摸摸你的头。"},
{en:"hair",ph:"/heər/",zh:"头发",e:"💇",g:1,se:"My hair is black.",sz:"我的头发是黑色的。"},
{en:"face",ph:"/feɪs/",zh:"脸",e:"😊",g:1,se:"Wash your face.",sz:"洗洗你的脸。"},
{en:"eye",ph:"/aɪ/",zh:"眼睛",e:"👀",g:1,se:"I have two eyes.",sz:"我有两只眼睛。"},
{en:"ear",ph:"/ɪər/",zh:"耳朵",e:"👂",g:1,se:"I have two ears.",sz:"我有两只耳朵。"},
{en:"nose",ph:"/nəʊz/",zh:"鼻子",e:"👃",g:1,se:"Touch your nose.",sz:"摸摸你的鼻子。"},
{en:"mouth",ph:"/maʊθ/",zh:"嘴",e:"👄",g:1,se:"Open your mouth.",sz:"张开你的嘴。"},
{en:"hand",ph:"/hænd/",zh:"手",e:"✋",g:1,se:"Wash your hands.",sz:"洗洗你的手。"},
{en:"arm",ph:"/ɑːm/",zh:"手臂",e:"💪",g:1,se:"My arms are long.",sz:"我的手臂很长。"},
{en:"leg",ph:"/leɡ/",zh:"腿",e:"🦵",g:1,se:"My legs are long.",sz:"我的腿很长。"},
{en:"foot",ph:"/fʊt/",zh:"脚",e:"🦶",g:1,se:"My foot hurts.",sz:"我的脚疼。"},
{en:"cat",ph:"/kæt/",zh:"猫",e:"🐱",g:1,se:"The cat is cute.",sz:"小猫很可爱。"},
{en:"dog",ph:"/dɒɡ/",zh:"狗",e:"🐶",g:1,se:"The dog can run.",sz:"狗会跑。"},
{en:"duck",ph:"/dʌk/",zh:"鸭子",e:"🦆",g:1,se:"The duck can swim.",sz:"鸭子会游泳。"},
{en:"bird",ph:"/bɜːd/",zh:"鸟",e:"🐦",g:1,se:"The bird can fly.",sz:"鸟会飞。"},
{en:"fish",ph:"/fɪʃ/",zh:"鱼",e:"🐟",g:1,se:"I like fish.",sz:"我喜欢鱼。"},
{en:"egg",ph:"/eɡ/",zh:"鸡蛋",e:"🥚",g:1,se:"I eat an egg.",sz:"我吃一个鸡蛋。"},
{en:"apple",ph:"/ˈæp.əl/",zh:"苹果",e:"🍎",g:1,se:"I like apples.",sz:"我喜欢苹果。"},
{en:"banana",ph:"/bəˈnɑː.nə/",zh:"香蕉",e:"🍌",g:1,se:"The banana is yellow.",sz:"香蕉是黄色的。"},
{en:"pear",ph:"/peər/",zh:"梨",e:"🍐",g:1,se:"The pear is sweet.",sz:"梨很甜。"},
{en:"orange",ph:"/ˈɒr.ɪndʒ/",zh:"橙子",e:"🍊",g:1,se:"I eat an orange.",sz:"我吃一个橙子。"},
{en:"mango",ph:"/ˈmæŋ.ɡəʊ/",zh:"芒果",e:"🥭",g:1,se:"I like mangoes.",sz:"我喜欢芒果。"},
{en:"milk",ph:"/mɪlk/",zh:"牛奶",e:"🥛",g:1,se:"I drink milk.",sz:"我喝牛奶。"},
{en:"mom",ph:"/mɒm/",zh:"妈妈",e:"👩",g:1,se:"I love my mom.",sz:"我爱我的妈妈。"},
{en:"dad",ph:"/dæd/",zh:"爸爸",e:"👨",g:1,se:"My dad is tall.",sz:"我爸爸很高。"},
{en:"good",ph:"/ɡʊd/",zh:"好的",e:"👍",g:1,se:"Good morning!",sz:"早上好！"},
{en:"hello",ph:"/həˈləʊ/",zh:"你好",e:"👋",g:1,se:"Hello, I am Ben.",sz:"你好，我是本。"},
{en:"hi",ph:"/haɪ/",zh:"嗨",e:"✌️",g:1,se:"Hi, how are you?",sz:"嗨，你好吗？"},
{en:"yes",ph:"/jes/",zh:"是",e:"✅",g:1,se:"Yes, I do.",sz:"是的，我喜欢。"},
{en:"no",ph:"/nəʊ/",zh:"不",e:"❌",g:1,se:"No, I don't.",sz:"不，我不喜欢。"},
{en:"thank",ph:"/θæŋk/",zh:"谢谢",e:"🙏",g:1,se:"Thank you.",sz:"谢谢你。"},
{en:"sorry",ph:"/ˈsɒr.i/",zh:"对不起",e:"😔",g:1,se:"I am sorry.",sz:"对不起。"},
{en:"bye",ph:"/baɪ/",zh:"再见",e:"👋",g:1,se:"Bye, see you!",sz:"再见，回头见！"},
/* ---- 二年级（食物·家庭·动物·自然）---- */
{en:"bread",ph:"/bred/",zh:"面包",e:"🍞",g:2,se:"I eat bread for breakfast.",sz:"我早餐吃面包。"},
{en:"rice",ph:"/raɪs/",zh:"米饭",e:"🍚",g:2,se:"I like rice.",sz:"我喜欢米饭。"},
{en:"meat",ph:"/miːt/",zh:"肉",e:"🍖",g:2,se:"I eat meat.",sz:"我吃肉。"},
{en:"soup",ph:"/suːp/",zh:"汤",e:"🍲",g:2,se:"The soup is hot.",sz:"汤很烫。"},
{en:"juice",ph:"/dʒuːs/",zh:"果汁",e:"🧃",g:2,se:"I drink juice.",sz:"我喝果汁。"},
{en:"tea",ph:"/tiː/",zh:"茶",e:"🍵",g:2,se:"Grandpa drinks tea.",sz:"爷爷喝茶。"},
{en:"water",ph:"/ˈwɔː.tər/",zh:"水",e:"💧",g:2,se:"I want some water.",sz:"我想要一些水。"},
{en:"cake",ph:"/keɪk/",zh:"蛋糕",e:"🍰",g:2,se:"The cake is sweet.",sz:"蛋糕很甜。"},
{en:"cookie",ph:"/ˈkʊk.i/",zh:"饼干",e:"🍪",g:2,se:"I like cookies.",sz:"我喜欢饼干。"},
{en:"noodle",ph:"/ˈnuː.dəl/",zh:"面条",e:"🍜",g:2,se:"I eat noodles.",sz:"我吃面条。"},
{en:"ice cream",ph:"/aɪs kriːm/",zh:"冰淇淋",e:"🍦",g:2,se:"I like ice cream.",sz:"我喜欢冰淇淋。"},
{en:"candy",ph:"/ˈkæn.di/",zh:"糖果",e:"🍬",g:2,se:"Don't eat too much candy.",sz:"别吃太多糖果。"},
{en:"fruit",ph:"/fruːt/",zh:"水果",e:"🍓",g:2,se:"Fruit is healthy.",sz:"水果很健康。"},
{en:"vegetable",ph:"/ˈvedʒ.tə.bəl/",zh:"蔬菜",e:"🥦",g:2,se:"Eat vegetables.",sz:"要吃蔬菜。"},
{en:"father",ph:"/ˈfɑː.ðər/",zh:"爸爸",e:"👨",g:2,se:"My father is strong.",sz:"我爸爸很强壮。"},
{en:"mother",ph:"/ˈmʌð.ər/",zh:"妈妈",e:"👩",g:2,se:"My mother is kind.",sz:"我妈妈很和蔼。"},
{en:"brother",ph:"/ˈbrʌð.ər/",zh:"兄弟",e:"👦",g:2,se:"My brother is tall.",sz:"我哥哥很高。"},
{en:"sister",ph:"/ˈsɪs.tər/",zh:"姐妹",e:"👧",g:2,se:"My sister is small.",sz:"我妹妹很小。"},
{en:"grandpa",ph:"/ˈɡræn.pɑː/",zh:"爷爷",e:"👴",g:2,se:"Grandpa is old.",sz:"爷爷年纪大了。"},
{en:"grandma",ph:"/ˈɡræn.mɑː/",zh:"奶奶",e:"👵",g:2,se:"Grandma cooks well.",sz:"奶奶做饭很好吃。"},
{en:"baby",ph:"/ˈbeɪ.bi/",zh:"宝宝",e:"👶",g:2,se:"The baby is sleeping.",sz:"宝宝在睡觉。"},
{en:"family",ph:"/ˈfæm.əl.i/",zh:"家庭",e:"👨‍👩‍👧",g:2,se:"I love my family.",sz:"我爱我的家。"},
{en:"uncle",ph:"/ˈʌŋ.kəl/",zh:"叔叔/舅舅",e:"🧔",g:2,se:"My uncle is a teacher.",sz:"我叔叔是老师。"},
{en:"aunt",ph:"/ɑːnt/",zh:"阿姨/姑姑",e:"👩",g:2,se:"My aunt is nice.",sz:"我姑姑人很好。"},
{en:"friend",ph:"/frend/",zh:"朋友",e:"🤝",g:2,se:"Tom is my friend.",sz:"汤姆是我的朋友。"},
{en:"pig",ph:"/pɪɡ/",zh:"猪",e:"🐷",g:2,se:"The pig is fat.",sz:"猪很胖。"},
{en:"cow",ph:"/kaʊ/",zh:"奶牛",e:"🐮",g:2,se:"The cow gives milk.",sz:"奶牛产奶。"},
{en:"sheep",ph:"/ʃiːp/",zh:"绵羊",e:"🐑",g:2,se:"The sheep is white.",sz:"绵羊是白色的。"},
{en:"horse",ph:"/hɔːs/",zh:"马",e:"🐴",g:2,se:"The horse can run fast.",sz:"马跑得很快。"},
{en:"rabbit",ph:"/ˈræb.ɪt/",zh:"兔子",e:"🐰",g:2,se:"The rabbit is white.",sz:"兔子是白色的。"},
{en:"bear",ph:"/beər/",zh:"熊",e:"🐻",g:2,se:"The bear is big.",sz:"熊很大。"},
{en:"tiger",ph:"/ˈtaɪ.ɡər/",zh:"老虎",e:"🐯",g:2,se:"The tiger is strong.",sz:"老虎很强壮。"},
{en:"lion",ph:"/ˈlaɪ.ən/",zh:"狮子",e:"🦁",g:2,se:"The lion is the king.",sz:"狮子是百兽之王。"},
{en:"monkey",ph:"/ˈmʌŋ.ki/",zh:"猴子",e:"🐵",g:2,se:"The monkey likes bananas.",sz:"猴子喜欢香蕉。"},
{en:"panda",ph:"/ˈpæn.də/",zh:"熊猫",e:"🐼",g:2,se:"The panda is cute.",sz:"熊猫很可爱。"},
{en:"frog",ph:"/frɒɡ/",zh:"青蛙",e:"🐸",g:2,se:"The frog can jump.",sz:"青蛙会跳。"},
{en:"snake",ph:"/sneɪk/",zh:"蛇",e:"🐍",g:2,se:"The snake is long.",sz:"蛇很长。"},
{en:"bee",ph:"/biː/",zh:"蜜蜂",e:"🐝",g:2,se:"The bee makes honey.",sz:"蜜蜂酿蜜。"},
{en:"butterfly",ph:"/ˈbʌt.ə.flaɪ/",zh:"蝴蝶",e:"🦋",g:2,se:"The butterfly is pretty.",sz:"蝴蝶很美。"},
{en:"sun",ph:"/sʌn/",zh:"太阳",e:"☀️",g:2,se:"The sun is hot.",sz:"太阳很热。"},
{en:"moon",ph:"/muːn/",zh:"月亮",e:"🌙",g:2,se:"The moon is round.",sz:"月亮是圆的。"},
{en:"star",ph:"/stɑː/",zh:"星星",e:"⭐",g:2,se:"I see a star.",sz:"我看见一颗星星。"},
{en:"sky",ph:"/skaɪ/",zh:"天空",e:"🌌",g:2,se:"The sky is blue.",sz:"天空是蓝色的。"},
{en:"tree",ph:"/triː/",zh:"树",e:"🌳",g:2,se:"The tree is tall.",sz:"树很高。"},
{en:"flower",ph:"/ˈflaʊ.ər/",zh:"花",e:"🌸",g:2,se:"The flower is red.",sz:"花是红色的。"},
{en:"grass",ph:"/ɡrɑːs/",zh:"草",e:"🌿",g:2,se:"The grass is green.",sz:"草是绿色的。"},
{en:"cloud",ph:"/klaʊd/",zh:"云",e:"☁️",g:2,se:"The cloud is white.",sz:"云是白色的。"},
{en:"rain",ph:"/reɪn/",zh:"雨",e:"🌧️",g:2,se:"It is raining.",sz:"正在下雨。"},
{en:"snow",ph:"/snəʊ/",zh:"雪",e:"❄️",g:2,se:"It is snowing.",sz:"正在下雪。"},
{en:"wind",ph:"/wɪnd/",zh:"风",e:"🌬️",g:2,se:"The wind is strong.",sz:"风很大。"},
{en:"mountain",ph:"/ˈmaʊn.tɪn/",zh:"山",e:"⛰️",g:2,se:"The mountain is high.",sz:"山很高。"},
{en:"river",ph:"/ˈrɪv.ər/",zh:"河",e:"🌊",g:2,se:"The river is long.",sz:"河很长。"},
{en:"sea",ph:"/siː/",zh:"大海",e:"🌊",g:2,se:"The sea is blue.",sz:"大海是蓝色的。"},
{en:"hot",ph:"/hɒt/",zh:"热",e:"🔥",g:2,se:"It is hot today.",sz:"今天很热。"},
{en:"cold",ph:"/kəʊld/",zh:"冷",e:"❄️",g:2,se:"It is cold in winter.",sz:"冬天很冷。"},
{en:"warm",ph:"/wɔːm/",zh:"温暖",e:"🌡️",g:2,se:"It is warm in spring.",sz:"春天很温暖。"},
{en:"cool",ph:"/kuːl/",zh:"凉爽",e:"😎",g:2,se:"It is cool today.",sz:"今天很凉爽。"},
{en:"happy",ph:"/ˈhæp.i/",zh:"快乐",e:"😊",g:2,se:"I am happy.",sz:"我很开心。"},
/* ---- 三年级（衣物·动作·时间·方位）---- */
{en:"shirt",ph:"/ʃɜːt/",zh:"衬衫",e:"👕",g:3,se:"My shirt is white.",sz:"我的衬衫是白色的。"},
{en:"dress",ph:"/dres/",zh:"连衣裙",e:"👗",g:3,se:"Her dress is red.",sz:"她的连衣裙是红色的。"},
{en:"shoe",ph:"/ʃuː/",zh:"鞋",e:"👟",g:3,se:"My shoes are new.",sz:"我的鞋子是新的。"},
{en:"hat",ph:"/hæt/",zh:"帽子",e:"🎩",g:3,se:"The hat is nice.",sz:"帽子很漂亮。"},
{en:"sock",ph:"/sɒk/",zh:"袜子",e:"🧦",g:3,se:"I have two socks.",sz:"我有两只袜子。"},
{en:"coat",ph:"/kəʊt/",zh:"外套",e:"🧥",g:3,se:"Put on your coat.",sz:"穿上你的外套。"},
{en:"sweater",ph:"/ˈswet.ər/",zh:"毛衣",e:"🧶",g:3,se:"This sweater is warm.",sz:"这件毛衣很暖和。"},
{en:"pants",ph:"/pænts/",zh:"裤子",e:"👖",g:3,se:"My pants are blue.",sz:"我的裤子是蓝色的。"},
{en:"shorts",ph:"/ʃɔːts/",zh:"短裤",e:"🩳",g:3,se:"He wears shorts.",sz:"他穿着短裤。"},
{en:"cap",ph:"/kæp/",zh:"棒球帽",e:"🧢",g:3,se:"The cap is on my head.",sz:"帽子在我头上。"},
{en:"run",ph:"/rʌn/",zh:"跑",e:"🏃",g:3,se:"I can run fast.",sz:"我跑得很快。"},
{en:"jump",ph:"/dʒʌmp/",zh:"跳",e:"🤾",g:3,se:"I can jump high.",sz:"我跳得很高。"},
{en:"walk",ph:"/wɔːk/",zh:"走",e:"🚶",g:3,se:"I walk to school.",sz:"我走路去上学。"},
{en:"swim",ph:"/swɪm/",zh:"游泳",e:"🏊",g:3,se:"I can swim.",sz:"我会游泳。"},
{en:"sing",ph:"/sɪŋ/",zh:"唱歌",e:"🎤",g:3,se:"I can sing.",sz:"我会唱歌。"},
{en:"dance",ph:"/dɑːns/",zh:"跳舞",e:"💃",g:3,se:"She can dance.",sz:"她会跳舞。"},
{en:"read",ph:"/riːd/",zh:"阅读",e:"📚",g:3,se:"I read a book.",sz:"我读一本书。"},
{en:"write",ph:"/raɪt/",zh:"写",e:"✍️",g:3,se:"I write my name.",sz:"我写我的名字。"},
{en:"draw",ph:"/drɔː/",zh:"画",e:"🎨",g:3,se:"I draw a cat.",sz:"我画一只猫。"},
{en:"play",ph:"/pleɪ/",zh:"玩",e:"🎮",g:3,se:"Let's play.",sz:"我们一起玩吧。"},
{en:"eat",ph:"/iːt/",zh:"吃",e:"🍴",g:3,se:"I eat rice.",sz:"我吃米饭。"},
{en:"sleep",ph:"/sliːp/",zh:"睡觉",e:"😴",g:3,se:"I sleep at night.",sz:"我晚上睡觉。"},
{en:"open",ph:"/ˈəʊ.pən/",zh:"打开",e:"🔓",g:3,se:"Open the door.",sz:"打开门。"},
{en:"close",ph:"/kləʊz/",zh:"关上",e:"🔒",g:3,se:"Close the window.",sz:"关上窗户。"},
{en:"help",ph:"/help/",zh:"帮助",e:"🤝",g:3,se:"Can you help me?",sz:"你能帮我吗？"},
{en:"give",ph:"/ɡɪv/",zh:"给",e:"🎁",g:3,se:"Give me a book.",sz:"给我一本书。"},
{en:"laugh",ph:"/lɑːf/",zh:"笑",e:"😄",g:3,se:"We laugh happily.",sz:"我们开心地笑。"},
{en:"cry",ph:"/kraɪ/",zh:"哭",e:"😭",g:3,se:"Don't cry.",sz:"别哭。"},
{en:"look",ph:"/lʊk/",zh:"看",e:"👀",g:3,se:"Look at the picture.",sz:"看这幅画。"},
{en:"listen",ph:"/ˈlɪs.ən/",zh:"听",e:"👂",g:3,se:"Listen to me.",sz:"听我说。"},
{en:"morning",ph:"/ˈmɔː.nɪŋ/",zh:"早晨",e:"🌅",g:3,se:"Good morning!",sz:"早上好！"},
{en:"afternoon",ph:"/ˌɑːf.təˈnuːn/",zh:"下午",e:"🌇",g:3,se:"Good afternoon!",sz:"下午好！"},
{en:"evening",ph:"/ˈiːv.nɪŋ/",zh:"傍晚",e:"🌆",g:3,se:"Good evening!",sz:"晚上好！"},
{en:"night",ph:"/naɪt/",zh:"夜晚",e:"🌙",g:3,se:"Good night!",sz:"晚安！"},
{en:"today",ph:"/təˈdeɪ/",zh:"今天",e:"📅",g:3,se:"It is sunny today.",sz:"今天天气晴朗。"},
{en:"tomorrow",ph:"/təˈmɒr.əʊ/",zh:"明天",e:"📆",g:3,se:"See you tomorrow.",sz:"明天见。"},
{en:"yesterday",ph:"/ˈjes.tə.deɪ/",zh:"昨天",e:"📅",g:3,se:"Yesterday was fun.",sz:"昨天很好玩。"},
{en:"week",ph:"/wiːk/",zh:"星期",e:"🗓️",g:3,se:"A week has seven days.",sz:"一星期有七天。"},
{en:"year",ph:"/jɪər/",zh:"年",e:"🎊",g:3,se:"Happy New Year!",sz:"新年快乐！"},
{en:"now",ph:"/naʊ/",zh:"现在",e:"⏰",g:3,se:"I am at school now.",sz:"我现在在学校。"},
{en:"in",ph:"/ɪn/",zh:"在……里面",e:"📥",g:3,se:"The cat is in the box.",sz:"猫在盒子里。"},
{en:"on",ph:"/ɒn/",zh:"在……上面",e:"📤",g:3,se:"The book is on the desk.",sz:"书在书桌上。"},
{en:"under",ph:"/ˈʌn.dər/",zh:"在……下面",e:"⬇️",g:3,se:"The ball is under the chair.",sz:"球在椅子下面。"},
{en:"behind",ph:"/bɪˈhaɪnd/",zh:"在……后面",e:"⬅️",g:3,se:"The dog is behind the door.",sz:"狗在门后面。"},
{en:"at",ph:"/æt/",zh:"在（某处）",e:"📍",g:3,se:"I am at home.",sz:"我在家。"},
{en:"hundred",ph:"/ˈhʌn.drəd/",zh:"百",e:"💯",g:3,se:"One hundred stars!",sz:"一百颗星星！"},
{en:"big",ph:"/bɪɡ/",zh:"大的",e:"🐘",g:3,se:"The elephant is big.",sz:"大象很大。"},
{en:"small",ph:"/smɔːl/",zh:"小的",e:"🐭",g:3,se:"The mouse is small.",sz:"老鼠很小。"},
{en:"tall",ph:"/tɔːl/",zh:"高的",e:"🦒",g:3,se:"The giraffe is tall.",sz:"长颈鹿很高。"},
{en:"short",ph:"/ʃɔːt/",zh:"矮的",e:"🐧",g:3,se:"The penguin is short.",sz:"企鹅很矮。"},
{en:"long",ph:"/lɒŋ/",zh:"长的",e:"🐍",g:3,se:"The snake is long.",sz:"蛇很长。"},
{en:"fat",ph:"/fæt/",zh:"胖的",e:"🐷",g:3,se:"The pig is fat.",sz:"猪很胖。"},
{en:"thin",ph:"/θɪn/",zh:"瘦的",e:"🦩",g:3,se:"The bird is thin.",sz:"这只鸟很瘦。"},
{en:"new",ph:"/njuː/",zh:"新的",e:"✨",g:3,se:"I have a new bag.",sz:"我有一个新书包。"},
{en:"old",ph:"/əʊld/",zh:"旧的",e:"🕰️",g:3,se:"My shoes are old.",sz:"我的鞋子旧了。"},
{en:"color",ph:"/ˈkʌl.ər/",zh:"颜色",e:"🎨",g:3,se:"What color is it?",sz:"它是什么颜色？"},
/* ---- 四年级（地点·交通·月份·星期·职业）---- */
{en:"home",ph:"/həʊm/",zh:"家",e:"🏠",g:4,se:"I go home.",sz:"我回家。"},
{en:"park",ph:"/pɑːk/",zh:"公园",e:"🏞️",g:4,se:"Let's go to the park.",sz:"我们去公园吧。"},
{en:"zoo",ph:"/zuː/",zh:"动物园",e:"🦁",g:4,se:"I see a lion at the zoo.",sz:"我在动物园看见狮子。"},
{en:"shop",ph:"/ʃɒp/",zh:"商店",e:"🏪",g:4,se:"The shop is near.",sz:"商店很近。"},
{en:"hospital",ph:"/ˈhɒs.pɪ.təl/",zh:"医院",e:"🏥",g:4,se:"The hospital is big.",sz:"医院很大。"},
{en:"library",ph:"/ˈlaɪ.brər.i/",zh:"图书馆",e:"📚",g:4,se:"I read in the library.",sz:"我在图书馆读书。"},
{en:"supermarket",ph:"/ˈsuː.pəˌmɑː.kɪt/",zh:"超市",e:"🛒",g:4,se:"Mom goes to the supermarket.",sz:"妈妈去超市。"},
{en:"cinema",ph:"/ˈsɪn.ə.mə/",zh:"电影院",e:"🎬",g:4,se:"We see a film at the cinema.",sz:"我们在电影院看电影。"},
{en:"restaurant",ph:"/ˈres.tər.ɒnt/",zh:"餐厅",e:"🍽️",g:4,se:"We eat in the restaurant.",sz:"我们在餐厅吃饭。"},
{en:"street",ph:"/striːt/",zh:"街道",e:"🛣️",g:4,se:"The street is long.",sz:"街道很长。"},
{en:"bridge",ph:"/brɪdʒ/",zh:"桥",e:"🌉",g:4,se:"The bridge is over the river.",sz:"桥在河上。"},
{en:"farm",ph:"/fɑːm/",zh:"农场",e:"🚜",g:4,se:"The farm has many animals.",sz:"农场里有很多动物。"},
{en:"car",ph:"/kɑː/",zh:"汽车",e:"🚗",g:4,se:"My dad drives a car.",sz:"我爸爸开汽车。"},
{en:"bus",ph:"/bʌs/",zh:"公交车",e:"🚌",g:4,se:"I go to school by bus.",sz:"我坐公交车上学。"},
{en:"train",ph:"/treɪn/",zh:"火车",e:"🚆",g:4,se:"The train is fast.",sz:"火车很快。"},
{en:"bike",ph:"/baɪk/",zh:"自行车",e:"🚲",g:4,se:"I ride a bike.",sz:"我骑自行车。"},
{en:"boat",ph:"/bəʊt/",zh:"小船",e:"⛵",g:4,se:"We take a boat.",sz:"我们坐船。"},
{en:"plane",ph:"/pleɪn/",zh:"飞机",e:"✈️",g:4,se:"The plane flies high.",sz:"飞机飞得很高。"},
{en:"ship",ph:"/ʃɪp/",zh:"大船",e:"🚢",g:4,se:"The ship is big.",sz:"轮船很大。"},
{en:"taxi",ph:"/ˈtæk.si/",zh:"出租车",e:"🚕",g:4,se:"We take a taxi.",sz:"我们坐出租车。"},
{en:"January",ph:"/ˈdʒæn.ju.ər.i/",zh:"一月",e:"📅",g:4,se:"January is cold.",sz:"一月很冷。"},
{en:"February",ph:"/ˈfeb.ru.ər.i/",zh:"二月",e:"📅",g:4,se:"February has 28 days.",sz:"二月有28天。"},
{en:"March",ph:"/mɑːtʃ/",zh:"三月",e:"📅",g:4,se:"Spring comes in March.",sz:"春天三月到来。"},
{en:"April",ph:"/ˈeɪ.prəl/",zh:"四月",e:"📅",g:4,se:"April is warm.",sz:"四月很温暖。"},
{en:"May",ph:"/meɪ/",zh:"五月",e:"📅",g:4,se:"May is my favorite month.",sz:"五月是我最喜欢的月份。"},
{en:"June",ph:"/dʒuːn/",zh:"六月",e:"📅",g:4,se:"June is hot.",sz:"六月很热。"},
{en:"July",ph:"/dʒʊˈlaɪ/",zh:"七月",e:"📅",g:4,se:"Summer is in July.",sz:"七月是夏天。"},
{en:"August",ph:"/ˈɔː.ɡəst/",zh:"八月",e:"📅",g:4,se:"August is hot.",sz:"八月很热。"},
{en:"September",ph:"/sepˈtem.bər/",zh:"九月",e:"📅",g:4,se:"School starts in September.",sz:"九月开学。"},
{en:"October",ph:"/ɒkˈtəʊ.bər/",zh:"十月",e:"📅",g:4,se:"October is cool.",sz:"十月很凉爽。"},
{en:"November",ph:"/nəʊˈvem.bər/",zh:"十一月",e:"📅",g:4,se:"November is cold.",sz:"十一月很冷。"},
{en:"December",ph:"/dɪˈsem.bər/",zh:"十二月",e:"📅",g:4,se:"December has Christmas.",sz:"十二月有圣诞节。"},
{en:"Monday",ph:"/ˈmʌn.deɪ/",zh:"星期一",e:"📅",g:4,se:"Monday is the first day.",sz:"星期一是第一天。"},
{en:"Tuesday",ph:"/ˈtjuːz.deɪ/",zh:"星期二",e:"📅",g:4,se:"We have music on Tuesday.",sz:"我们星期二有音乐课。"},
{en:"Wednesday",ph:"/ˈwenz.deɪ/",zh:"星期三",e:"📅",g:4,se:"Wednesday is in the middle.",sz:"星期三在中间。"},
{en:"Thursday",ph:"/ˈθɜːz.deɪ/",zh:"星期四",e:"📅",g:4,se:"We have PE on Thursday.",sz:"我们星期四有体育课。"},
{en:"Friday",ph:"/ˈfraɪ.deɪ/",zh:"星期五",e:"📅",g:4,se:"Friday is my favorite.",sz:"星期五是我的最爱。"},
{en:"Saturday",ph:"/ˈsæt.ə.deɪ/",zh:"星期六",e:"📅",g:4,se:"I play on Saturday.",sz:"我星期六玩。"},
{en:"Sunday",ph:"/ˈsʌn.deɪ/",zh:"星期日",e:"📅",g:4,se:"Sunday is a rest day.",sz:"星期天是休息日。"},
{en:"teacher",ph:"/ˈtiː.tʃər/",zh:"老师",e:"👩‍🏫",g:4,se:"My teacher is nice.",sz:"我的老师很好。"},
{en:"doctor",ph:"/ˈdɒk.tər/",zh:"医生",e:"🧑‍⚕️",g:4,se:"The doctor helps people.",sz:"医生帮助人们。"},
{en:"nurse",ph:"/nɜːs/",zh:"护士",e:"👩‍⚕️",g:4,se:"The nurse is kind.",sz:"护士很亲切。"},
{en:"farmer",ph:"/ˈfɑː.mər/",zh:"农民",e:"👨‍🌾",g:4,se:"The farmer grows rice.",sz:"农民种水稻。"},
{en:"worker",ph:"/ˈwɜː.kər/",zh:"工人",e:"👷",g:4,se:"The worker builds houses.",sz:"工人盖房子。"},
{en:"driver",ph:"/ˈdraɪ.vər/",zh:"司机",e:"🚗",g:4,se:"The driver drives the bus.",sz:"司机开公交车。"},
{en:"cook",ph:"/kʊk/",zh:"厨师",e:"👨‍🍳",g:4,se:"The cook makes food.",sz:"厨师做饭。"},
{en:"police",ph:"/pəˈliːs/",zh:"警察",e:"👮",g:4,se:"The police help us.",sz:"警察帮助我们。"},
{en:"pupil",ph:"/ˈpjuː.pəl/",zh:"小学生",e:"🧒",g:4,se:"I am a pupil.",sz:"我是个小学生。"},
{en:"classroom",ph:"/ˈklɑːs.ruːm/",zh:"教室",e:"🏫",g:4,se:"Our classroom is clean.",sz:"我们的教室很干净。"},
{en:"playground",ph:"/ˈpleɪ.ɡraʊnd/",zh:"操场",e:"⛳",g:4,se:"We play on the playground.",sz:"我们在操场上玩。"},
{en:"English",ph:"/ˈɪŋ.ɡlɪʃ/",zh:"英语",e:"🔤",g:4,se:"I learn English.",sz:"我学英语。"},
{en:"math",ph:"/mæθ/",zh:"数学",e:"🔢",g:4,se:"Math is fun.",sz:"数学很有趣。"},
{en:"music",ph:"/ˈmjuː.zɪk/",zh:"音乐",e:"🎵",g:4,se:"I like music.",sz:"我喜欢音乐。"},
{en:"art",ph:"/ɑːt/",zh:"美术",e:"🎨",g:4,se:"We draw in art class.",sz:"我们在美术课上画画。"},
{en:"science",ph:"/ˈsaɪ.əns/",zh:"科学",e:"🔬",g:4,se:"Science is interesting.",sz:"科学很有趣。"},
{en:"PE",ph:"/ˌpiːˈiː/",zh:"体育",e:"⚽",g:4,se:"We run in PE class.",sz:"我们在体育课上跑步。"},
/* ---- 五年级（学科·爱好·形容词·房间·家务）---- */
{en:"Chinese",ph:"/ˌtʃaɪˈniːz/",zh:"语文/中文",e:"🇨🇳",g:5,se:"I read Chinese books.",sz:"我读中文书。"},
{en:"computer",ph:"/kəmˈpjuː.tər/",zh:"电脑",e:"💻",g:5,se:"I play on the computer.",sz:"我玩电脑。"},
{en:"football",ph:"/ˈfʊt.bɔːl/",zh:"足球",e:"⚽",g:5,se:"I play football.",sz:"我踢足球。"},
{en:"basketball",ph:"/ˈbɑː.skɪt.bɔːl/",zh:"篮球",e:"🏀",g:5,se:"Basketball is fun.",sz:"篮球很有趣。"},
{en:"ping-pong",ph:"/ˈpɪŋ.pɒŋ/",zh:"乒乓球",e:"🏓",g:5,se:"We play ping-pong.",sz:"我们打乒乓球。"},
{en:"volleyball",ph:"/ˈvɒl.i.bɔːl/",zh:"排球",e:"🏐",g:5,se:"She plays volleyball.",sz:"她打排球。"},
{en:"tennis",ph:"/ˈten.ɪs/",zh:"网球",e:"🎾",g:5,se:"Tennis needs a racket.",sz:"打网球需要球拍。"},
{en:"badminton",ph:"/ˈbæd.mɪn.tən/",zh:"羽毛球",e:"🏸",g:5,se:"I like badminton.",sz:"我喜欢羽毛球。"},
{en:"swimming",ph:"/ˈswɪm.ɪŋ/",zh:"游泳",e:"🏊",g:5,se:"Swimming is good for you.",sz:"游泳对你有好处。"},
{en:"running",ph:"/ˈrʌn.ɪŋ/",zh:"跑步",e:"🏃",g:5,se:"Running is healthy.",sz:"跑步有益健康。"},
{en:"drawing",ph:"/ˈdrɔː.ɪŋ/",zh:"画画",e:"🎨",g:5,se:"I am good at drawing.",sz:"我擅长画画。"},
{en:"singing",ph:"/ˈsɪŋ.ɪŋ/",zh:"唱歌",e:"🎤",g:5,se:"Singing makes me happy.",sz:"唱歌让我开心。"},
{en:"dancing",ph:"/ˈdɑːn.sɪŋ/",zh:"跳舞",e:"💃",g:5,se:"She likes dancing.",sz:"她喜欢跳舞。"},
{en:"reading",ph:"/ˈriː.dɪŋ/",zh:"阅读",e:"📖",g:5,se:"Reading is a good habit.",sz:"阅读是好习惯。"},
{en:"hobby",ph:"/ˈhɒb.i/",zh:"爱好",e:"🧩",g:5,se:"My hobby is reading.",sz:"我的爱好是阅读。"},
{en:"clean",ph:"/kliːn/",zh:"干净的",e:"🧼",g:5,se:"The room is clean.",sz:"房间很干净。"},
{en:"dirty",ph:"/ˈdɜː.ti/",zh:"脏的",e:"🪣",g:5,se:"My shoes are dirty.",sz:"我的鞋脏了。"},
{en:"fast",ph:"/fɑːst/",zh:"快的",e:"💨",g:5,se:"The train is fast.",sz:"火车很快。"},
{en:"slow",ph:"/sləʊ/",zh:"慢的",e:"🐢",g:5,se:"The turtle is slow.",sz:"乌龟很慢。"},
{en:"quiet",ph:"/ˈkwaɪ.ət/",zh:"安静的",e:"🤫",g:5,se:"Be quiet, please.",sz:"请安静。"},
{en:"loud",ph:"/laʊd/",zh:"大声的",e:"📢",g:5,se:"The music is loud.",sz:"音乐声很大。"},
{en:"beautiful",ph:"/ˈbjuː.tɪ.fəl/",zh:"美丽的",e:"🌸",g:5,se:"The flower is beautiful.",sz:"花很美丽。"},
{en:"clever",ph:"/ˈklev.ər/",zh:"聪明的",e:"🧠",g:5,se:"The monkey is clever.",sz:"猴子很聪明。"},
{en:"kind",ph:"/kaɪnd/",zh:"和蔼的",e:"💕",g:5,se:"My grandma is kind.",sz:"我奶奶很和蔼。"},
{en:"friendly",ph:"/ˈfrend.li/",zh:"友好的",e:"😊",g:5,se:"My classmates are friendly.",sz:"我的同学们很友好。"},
{en:"bedroom",ph:"/ˈbed.ruːm/",zh:"卧室",e:"🛏️",g:5,se:"I sleep in my bedroom.",sz:"我在卧室睡觉。"},
{en:"living room",ph:"/ˈlɪv.ɪŋ ruːm/",zh:"客厅",e:"🛋️",g:5,se:"We watch TV in the living room.",sz:"我们在客厅看电视。"},
{en:"kitchen",ph:"/ˈkɪtʃ.ɪn/",zh:"厨房",e:"🍳",g:5,se:"Mom cooks in the kitchen.",sz:"妈妈在厨房做饭。"},
{en:"bathroom",ph:"/ˈbɑːθ.ruːm/",zh:"浴室",e:"🛁",g:5,se:"I wash in the bathroom.",sz:"我在浴室洗漱。"},
{en:"study",ph:"/ˈstʌd.i/",zh:"书房",e:"📖",g:5,se:"Dad reads in the study.",sz:"爸爸在书房看书。"},
{en:"house",ph:"/haʊs/",zh:"房子",e:"🏠",g:5,se:"Our house is big.",sz:"我们的房子很大。"},
{en:"garden",ph:"/ˈɡɑː.dən/",zh:"花园",e:"🌷",g:5,se:"The garden has flowers.",sz:"花园里有花。"},
{en:"sweep",ph:"/swiːp/",zh:"扫地",e:"🧹",g:5,se:"I sweep the floor.",sz:"我扫地。"},
{en:"wash",ph:"/wɒʃ/",zh:"洗",e:"🧼",g:5,se:"I wash the dishes.",sz:"我洗碗。"},
{en:"kite",ph:"/kaɪt/",zh:"风筝",e:"🪁",g:5,se:"The kite is high.",sz:"风筝飞得很高。"},
{en:"fly",ph:"/flaɪ/",zh:"放飞",e:"🪁",g:5,se:"I fly a kite.",sz:"我放风筝。"},
{en:"climb",ph:"/klaɪm/",zh:"爬",e:"🧗",g:5,se:"We climb the hill.",sz:"我们爬山。"},
{en:"slide",ph:"/slaɪd/",zh:"滑梯",e:"🛝",g:5,se:"I like the slide.",sz:"我喜欢滑梯。"},
{en:"swing",ph:"/swɪŋ/",zh:"秋千",e:"🎠",g:5,se:"I play on the swing.",sz:"我荡秋千。"},
{en:"spring",ph:"/sprɪŋ/",zh:"春天",e:"🌸",g:5,se:"Spring is warm.",sz:"春天很温暖。"},
{en:"summer",ph:"/ˈsʌm.ər/",zh:"夏天",e:"☀️",g:5,se:"Summer is hot.",sz:"夏天很热。"},
{en:"autumn",ph:"/ˈɔː.təm/",zh:"秋天",e:"🍂",g:5,se:"Autumn is cool.",sz:"秋天很凉爽。"},
{en:"winter",ph:"/ˈwɪn.tər/",zh:"冬天",e:"❄️",g:5,se:"Winter is cold.",sz:"冬天很冷。"},
{en:"season",ph:"/ˈsiː.zən/",zh:"季节",e:"🍃",g:5,se:"There are four seasons.",sz:"一年有四季。"},
{en:"weather",ph:"/ˈweð.ər/",zh:"天气",e:"🌤️",g:5,se:"The weather is nice.",sz:"天气很好。"},
{en:"sunny",ph:"/ˈsʌn.i/",zh:"晴朗的",e:"☀️",g:5,se:"It is sunny today.",sz:"今天阳光明媚。"},
{en:"rainy",ph:"/ˈreɪ.ni/",zh:"下雨的",e:"🌧️",g:5,se:"It is rainy today.",sz:"今天下雨。"},
{en:"snowy",ph:"/ˈsnəʊ.i/",zh:"下雪的",e:"🌨️",g:5,se:"It is snowy today.",sz:"今天下雪。"},
{en:"windy",ph:"/ˈwɪn.di/",zh:"刮风的",e:"🌬️",g:5,se:"It is windy today.",sz:"今天刮风。"},
{en:"cloudy",ph:"/ˈklaʊ.di/",zh:"多云的",e:"☁️",g:5,se:"It is cloudy today.",sz:"今天多云。"},
{en:"clothes",ph:"/kləʊðz/",zh:"衣服",e:"👕",g:5,se:"My clothes are clean.",sz:"我的衣服很干净。"},
{en:"jacket",ph:"/ˈdʒæk.ɪt/",zh:"夹克",e:"🧥",g:5,se:"I wear a jacket.",sz:"我穿一件夹克。"},
{en:"gloves",ph:"/ɡlʌvz/",zh:"手套",e:"🧤",g:5,se:"Gloves keep hands warm.",sz:"手套让手暖和。"},
/* ---- 六年级（情绪·健康·旅行·计划·节日·过去式）---- */
{en:"angry",ph:"/ˈæŋ.ɡri/",zh:"生气的",e:"😠",g:6,se:"Don't be angry.",sz:"别生气。"},
{en:"tired",ph:"/ˈtaɪ.əd/",zh:"累的",e:"😴",g:6,se:"I am tired.",sz:"我累了。"},
{en:"scared",ph:"/skeəd/",zh:"害怕的",e:"😨",g:6,se:"I am scared of the dark.",sz:"我怕黑。"},
{en:"excited",ph:"/ɪkˈsaɪ.tɪd/",zh:"兴奋的",e:"🤩",g:6,se:"I am excited!",sz:"我很兴奋！"},
{en:"bored",ph:"/bɔːd/",zh:"无聊的",e:"🥱",g:6,se:"I am bored.",sz:"我好无聊。"},
{en:"nervous",ph:"/ˈnɜː.vəs/",zh:"紧张的",e:"😰",g:6,se:"I am nervous before the test.",sz:"考试前我紧张。"},
{en:"proud",ph:"/praʊd/",zh:"骄傲的",e:"🦚",g:6,se:"I am proud of you.",sz:"我为你骄傲。"},
{en:"headache",ph:"/ˈhed.eɪk/",zh:"头痛",e:"🤕",g:6,se:"I have a headache.",sz:"我头疼。"},
{en:"toothache",ph:"/ˈtuːθ.eɪk/",zh:"牙痛",e:"🦷",g:6,se:"I have a toothache.",sz:"我牙疼。"},
{en:"fever",ph:"/ˈfiː.vər/",zh:"发烧",e:"🤒",g:6,se:"I have a fever.",sz:"我发烧了。"},
{en:"cough",ph:"/kɒf/",zh:"咳嗽",e:"😷",g:6,se:"I have a cough.",sz:"我咳嗽。"},
{en:"medicine",ph:"/ˈmed.ɪ.sən/",zh:"药",e:"💊",g:6,se:"Take some medicine.",sz:"吃些药。"},
{en:"healthy",ph:"/ˈhel.θi/",zh:"健康的",e:"💪",g:6,se:"Eat healthy food.",sz:"吃健康的食物。"},
{en:"strong",ph:"/strɒŋ/",zh:"强壮的",e:"💪",g:6,se:"Exercise makes me strong.",sz:"运动让我强壮。"},
{en:"weak",ph:"/wiːk/",zh:"虚弱的",e:"🥀",g:6,se:"I feel weak.",sz:"我感觉虚弱。"},
{en:"visit",ph:"/ˈvɪz.ɪt/",zh:"拜访",e:"🏠",g:6,se:"I visit my grandma.",sz:"我去看望奶奶。"},
{en:"travel",ph:"/ˈtræv.əl/",zh:"旅行",e:"✈️",g:6,se:"I want to travel.",sz:"我想去旅行。"},
{en:"ticket",ph:"/ˈtɪk.ɪt/",zh:"票",e:"🎫",g:6,se:"I buy a ticket.",sz:"我买一张票。"},
{en:"map",ph:"/mæp/",zh:"地图",e:"🗺️",g:6,se:"Look at the map.",sz:"看地图。"},
{en:"camera",ph:"/ˈkæm.rə/",zh:"相机",e:"📷",g:6,se:"Take photos with a camera.",sz:"用相机拍照。"},
{en:"hotel",ph:"/həʊˈtel/",zh:"酒店",e:"🏨",g:6,se:"We stay in a hotel.",sz:"我们住在酒店。"},
{en:"gift",ph:"/ɡɪft/",zh:"礼物",e:"🎁",g:6,se:"The gift is for you.",sz:"礼物是给你的。"},
{en:"plan",ph:"/plæn/",zh:"计划",e:"📋",g:6,se:"I have a plan.",sz:"我有一个计划。"},
{en:"weekend",ph:"/ˌwiːkˈend/",zh:"周末",e:"🌈",g:6,se:"I play on the weekend.",sz:"我周末玩。"},
{en:"holiday",ph:"/ˈhɒl.ə.deɪ/",zh:"假期",e:"🏖️",g:6,se:"I love the holiday.",sz:"我喜欢假期。"},
{en:"festival",ph:"/ˈfes.tɪ.vəl/",zh:"节日",e:"🎉",g:6,se:"The festival is fun.",sz:"节日很有趣。"},
{en:"Christmas",ph:"/ˈkrɪs.məs/",zh:"圣诞节",e:"🎄",g:6,se:"Merry Christmas!",sz:"圣诞快乐！"},
{en:"birthday",ph:"/ˈbɜːθ.deɪ/",zh:"生日",e:"🎂",g:6,se:"Happy birthday!",sz:"生日快乐！"},
{en:"party",ph:"/ˈpɑː.ti/",zh:"聚会",e:"🎉",g:6,se:"We have a party.",sz:"我们开派对。"},
{en:"taller",ph:"/ˈtɔː.lər/",zh:"更高的",e:"🦒",g:6,se:"He is taller than me.",sz:"他比我高。"},
{en:"shorter",ph:"/ˈʃɔː.tər/",zh:"更矮的",e:"🐧",g:6,se:"I am shorter than him.",sz:"我比他矮。"},
{en:"bigger",ph:"/ˈbɪɡ.ər/",zh:"更大的",e:"🐘",g:6,se:"The elephant is bigger.",sz:"大象更大。"},
{en:"smaller",ph:"/ˈsmɔː.lər/",zh:"更小的",e:"🐭",g:6,se:"The mouse is smaller.",sz:"老鼠更小。"},
{en:"longer",ph:"/ˈlɒŋ.ɡər/",zh:"更长的",e:"🐍",g:6,se:"The river is longer.",sz:"这条河更长。"},
{en:"heavier",ph:"/ˈhev.i.ər/",zh:"更重的",e:"🐳",g:6,se:"The whale is heavier.",sz:"鲸鱼更重。"},
{en:"thinner",ph:"/ˈθɪn.ər/",zh:"更瘦的",e:"🦩",g:6,se:"She is thinner than me.",sz:"她比我瘦。"},
{en:"older",ph:"/ˈəʊl.dər/",zh:"更大的",e:"👴",g:6,se:"My brother is older.",sz:"我哥哥更大。"},
{en:"younger",ph:"/ˈjʌŋ.ɡər/",zh:"更小的",e:"👶",g:6,se:"My sister is younger.",sz:"我妹妹更小。"},
{en:"better",ph:"/ˈbet.ər/",zh:"更好的",e:"🌟",g:6,se:"I am better now.",sz:"我现在好多了。"},
{en:"best",ph:"/best/",zh:"最好的",e:"🏆",g:6,se:"She is my best friend.",sz:"她是我最好的朋友。"},
{en:"went",ph:"/went/",zh:"去（过去式）",e:"🚶",g:6,se:"I went to the park.",sz:"我去了公园。"},
{en:"had",ph:"/hæd/",zh:"有（过去式）",e:"⭐",g:6,se:"We had fun.",sz:"我们玩得很开心。"},
{en:"saw",ph:"/sɔː/",zh:"看见（过去式）",e:"👀",g:6,se:"I saw a bird.",sz:"我看见一只鸟。"},
{en:"ate",ph:"/eɪt/",zh:"吃（过去式）",e:"🍽️",g:6,se:"I ate an apple.",sz:"我吃了一个苹果。"},
{en:"drank",ph:"/dræŋk/",zh:"喝（过去式）",e:"🥤",g:6,se:"I drank some milk.",sz:"我喝了一些牛奶。"},
{en:"played",ph:"/pleɪd/",zh:"玩（过去式）",e:"🎮",g:6,se:"We played games.",sz:"我们玩了游戏。"},
{en:"visited",ph:"/ˈvɪz.ɪ.tɪd/",zh:"参观（过去式）",e:"🏛️",g:6,se:"I visited my uncle.",sz:"我去看了叔叔。"},
{en:"watched",ph:"/wɒtʃt/",zh:"看（过去式）",e:"📺",g:6,se:"I watched TV.",sz:"我看了电视。"},
{en:"was",ph:"/wɒz/",zh:"是（过去式）",e:"📖",g:6,se:"I was happy.",sz:"我很开心。"},
{en:"were",ph:"/wɜːr/",zh:"是（过去式）",e:"📖",g:6,se:"We were at school.",sz:"我们在学校。"},
{en:"first",ph:"/fɜːst/",zh:"第一的",e:"🥇",g:6,se:"I am first.",sz:"我是第一名。"},
{en:"second",ph:"/ˈsek.ənd/",zh:"第二的",e:"🥈",g:6,se:"I am second.",sz:"我是第二名。"},
{en:"third",ph:"/θɜːd/",zh:"第三的",e:"🥉",g:6,se:"I am third.",sz:"我是第三名。"},
{en:"together",ph:"/təˈɡeð.ər/",zh:"一起",e:"🤝",g:6,se:"We play together.",sz:"我们一起玩。"},
/* ---- 初一（校园·性格·是非·常用）---- */
{en:"subject",ph:"/ˈsʌb.dʒekt/",zh:"学科",e:"📚",g:7,se:"What is your favorite subject?",sz:"你最喜欢的学科是什么？"},
{en:"club",ph:"/klʌb/",zh:"社团",e:"🏅",g:7,se:"I join the art club.",sz:"我加入了美术社团。"},
{en:"date",ph:"/deɪt/",zh:"日期",e:"📅",g:7,se:"What is the date today?",sz:"今天几号？"},
{en:"favorite",ph:"/ˈfeɪ.vər.ɪt/",zh:"最喜欢的",e:"❤️",g:7,se:"Blue is my favorite color.",sz:"蓝色是我最喜欢的颜色。"},
{en:"because",ph:"/bɪˈkɒz/",zh:"因为",e:"💡",g:7,se:"I like it because it is fun.",sz:"我喜欢它因为它有趣。"},
{en:"interesting",ph:"/ˈɪn.trə.stɪŋ/",zh:"有趣的",e:"🧐",g:7,se:"The story is interesting.",sz:"故事很有趣。"},
{en:"boring",ph:"/ˈbɔː.rɪŋ/",zh:"无聊的",e:"🥱",g:7,se:"The film is boring.",sz:"电影很无聊。"},
{en:"difficult",ph:"/ˈdɪf.ɪ.kəlt/",zh:"困难的",e:"🧗",g:7,se:"The question is difficult.",sz:"问题很难。"},
{en:"easy",ph:"/ˈiː.zi/",zh:"容易的",e:"🍰",g:7,se:"The test is easy.",sz:"考试很简单。"},
{en:"useful",ph:"/ˈjuːs.fəl/",zh:"有用的",e:"🛠️",g:7,se:"This book is useful.",sz:"这本书很有用。"},
{en:"delicious",ph:"/dɪˈlɪʃ.əs/",zh:"美味的",e:"🍔",g:7,se:"The food is delicious.",sz:"食物很美味。"},
{en:"expensive",ph:"/ɪkˈspen.sɪv/",zh:"昂贵的",e:"💎",g:7,se:"The watch is expensive.",sz:"手表很贵。"},
{en:"cheap",ph:"/tʃiːp/",zh:"便宜的",e:"🏷️",g:7,se:"The toy is cheap.",sz:"玩具很便宜。"},
{en:"nice",ph:"/naɪs/",zh:"好的",e:"😊",g:7,se:"She is very nice.",sz:"她人很好。"},
{en:"polite",ph:"/pəˈlaɪt/",zh:"有礼貌的",e:"🎩",g:7,se:"Be polite to others.",sz:"对别人要有礼貌。"},
{en:"helpful",ph:"/ˈhelp.fəl/",zh:"乐于助人的",e:"🤝",g:7,se:"He is helpful.",sz:"他乐于助人。"},
{en:"smart",ph:"/smɑːt/",zh:"聪明的",e:"🧠",g:7,se:"She is smart.",sz:"她很聪明。"},
{en:"brave",ph:"/breɪv/",zh:"勇敢的",e:"🦁",g:7,se:"Be brave!",sz:"勇敢一点！"},
{en:"honest",ph:"/ˈɒn.ɪst/",zh:"诚实的",e:"🤝",g:7,se:"Be honest, please.",sz:"请诚实。"},
{en:"careful",ph:"/ˈkeə.fəl/",zh:"小心的",e:"⚠️",g:7,se:"Be careful!",sz:"小心！"},
{en:"careless",ph:"/ˈkeə.ləs/",zh:"粗心的",e:"😬",g:7,se:"Don't be careless.",sz:"别粗心。"},
{en:"early",ph:"/ˈɜː.li/",zh:"早的",e:"🌅",g:7,se:"I get up early.",sz:"我起得早。"},
{en:"late",ph:"/leɪt/",zh:"迟到的",e:"🕐",g:7,se:"Don't be late.",sz:"别迟到。"},
{en:"high",ph:"/haɪ/",zh:"高的",e:"⛰️",g:7,se:"The kite flies high.",sz:"风筝飞得高。"},
{en:"low",ph:"/ləʊ/",zh:"低的",e:"📉",g:7,se:"The plane flies low.",sz:"飞机飞得低。"},
{en:"right",ph:"/raɪt/",zh:"正确的",e:"✅",g:7,se:"You are right.",sz:"你是对的。"},
{en:"wrong",ph:"/rɒŋ/",zh:"错误的",e:"❌",g:7,se:"It is wrong.",sz:"这是错的。"},
{en:"true",ph:"/truː/",zh:"真实的",e:"💯",g:7,se:"It is true.",sz:"这是真的。"},
{en:"false",ph:"/fɔːls/",zh:"假的",e:"🚫",g:7,se:"The answer is false.",sz:"答案是错的。"},
{en:"idea",ph:"/aɪˈdɪə/",zh:"主意",e:"💡",g:7,se:"Good idea!",sz:"好主意！"},
{en:"problem",ph:"/ˈprɒb.ləm/",zh:"问题",e:"🤔",g:7,se:"No problem.",sz:"没问题。"},
{en:"answer",ph:"/ˈɑːn.sər/",zh:"答案",e:"✔️",g:7,se:"The answer is right.",sz:"答案是对的。"},
{en:"question",ph:"/ˈkwes.tʃən/",zh:"问题",e:"❓",g:7,se:"I have a question.",sz:"我有一个问题。"},
{en:"name",ph:"/neɪm/",zh:"名字",e:"🏷️",g:7,se:"My name is Tom.",sz:"我叫汤姆。"},
{en:"number",ph:"/ˈnʌm.bər/",zh:"数字",e:"🔢",g:7,se:"What is your phone number?",sz:"你的电话号码是多少？"},
{en:"phone",ph:"/fəʊn/",zh:"电话",e:"📱",g:7,se:"My phone is new.",sz:"我的手机是新的。"},
{en:"email",ph:"/ˈiː.meɪl/",zh:"电子邮件",e:"✉️",g:7,se:"Send me an email.",sz:"给我发封邮件。"},
{en:"classmate",ph:"/ˈklɑːs.meɪt/",zh:"同学",e:"🧑‍🎓",g:7,se:"Tom is my classmate.",sz:"汤姆是我的同学。"},
{en:"schoolbag",ph:"/ˈskuːl.bæɡ/",zh:"书包",e:"🎒",g:7,se:"My schoolbag is heavy.",sz:"我的书包很重。"},
{en:"dictionary",ph:"/ˈdɪk.ʃən.ər.i/",zh:"词典",e:"📕",g:7,se:"I use a dictionary.",sz:"我用词典。"},
{en:"picture",ph:"/ˈpɪk.tʃər/",zh:"图片",e:"🖼️",g:7,se:"Look at the picture.",sz:"看这幅图。"},
{en:"grey",ph:"/ɡreɪ/",zh:"灰色的",e:"🌫️",g:7,se:"The sky is grey.",sz:"天空是灰色的。"},
{en:"brown",ph:"/braʊn/",zh:"棕色的",e:"🟤",g:7,se:"I like brown.",sz:"我喜欢棕色。"},
{en:"purple",ph:"/ˈpɜː.pəl/",zh:"紫色的",e:"🟣",g:7,se:"The grape is purple.",sz:"葡萄是紫色的。"},
{en:"country",ph:"/ˈkʌn.tri/",zh:"国家",e:"🌍",g:7,se:"China is a big country.",sz:"中国是一个大国。"},
{en:"world",ph:"/wɜːld/",zh:"世界",e:"🌍",g:7,se:"I want to see the world.",sz:"我想去看看世界。"},
{en:"people",ph:"/ˈpiː.pəl/",zh:"人们",e:"👥",g:7,se:"Many people are here.",sz:"很多人在这里。"},
{en:"child",ph:"/tʃaɪld/",zh:"孩子",e:"🧒",g:7,se:"The child is happy.",sz:"这个孩子很开心。"},
/* ---- 初二（性格·学科·科技·环境）---- */
{en:"different",ph:"/ˈdɪf.ər.ənt/",zh:"不同的",e:"🎭",g:8,se:"We are different.",sz:"我们不一样。"},
{en:"same",ph:"/seɪm/",zh:"相同的",e:"🎯",g:8,se:"We are in the same class.",sz:"我们在同一个班。"},
{en:"popular",ph:"/ˈpɒp.jə.lər/",zh:"受欢迎的",e:"🌟",g:8,se:"He is popular at school.",sz:"他在学校很受欢迎。"},
{en:"special",ph:"/ˈspeʃ.əl/",zh:"特别的",e:"⭐",g:8,se:"Today is special.",sz:"今天是特别的。"},
{en:"important",ph:"/ɪmˈpɔː.tənt/",zh:"重要的",e:"🎖️",g:8,se:"Health is important.",sz:"健康很重要。"},
{en:"famous",ph:"/ˈfeɪ.məs/",zh:"著名的",e:"🏆",g:8,se:"He is a famous singer.",sz:"他是一位著名的歌手。"},
{en:"successful",ph:"/səkˈses.fəl/",zh:"成功的",e:"🏅",g:8,se:"She is successful.",sz:"她很成功。"},
{en:"confident",ph:"/ˈkɒn.fɪ.dənt/",zh:"自信的",e:"😎",g:8,se:"Be confident!",sz:"自信一点！"},
{en:"patient",ph:"/ˈpeɪ.ʃənt/",zh:"耐心的",e:"🧘",g:8,se:"The teacher is patient.",sz:"老师很有耐心。"},
{en:"active",ph:"/ˈæk.tɪv/",zh:"活跃的",e:"🏃",g:8,se:"He is active in class.",sz:"他在课堂上很活跃。"},
{en:"serious",ph:"/ˈsɪə.ri.əs/",zh:"严肃的",e:"😐",g:8,se:"He looks serious.",sz:"他看起来很严肃。"},
{en:"strict",ph:"/strɪkt/",zh:"严格的",e:"📏",g:8,se:"My teacher is strict.",sz:"我的老师很严格。"},
{en:"gentle",ph:"/ˈdʒen.təl/",zh:"温柔的",e:"🕊️",g:8,se:"She is gentle.",sz:"她很温柔。"},
{en:"humorous",ph:"/ˈhjuː.mə.rəs/",zh:"幽默的",e:"😂",g:8,se:"He is humorous.",sz:"他很幽默。"},
{en:"outgoing",ph:"/ˌaʊtˈɡəʊ.ɪŋ/",zh:"外向的",e:"🗣️",g:8,se:"She is outgoing.",sz:"她很外向。"},
{en:"shy",ph:"/ʃaɪ/",zh:"害羞的",e:"😳",g:8,se:"I am shy.",sz:"我害羞。"},
{en:"generous",ph:"/ˈdʒen.ə.rəs/",zh:"大方的",e:"🎁",g:8,se:"He is generous.",sz:"他很大方。"},
{en:"creative",ph:"/kriˈeɪ.tɪv/",zh:"有创造力的",e:"🎨",g:8,se:"She is creative.",sz:"她很有创造力。"},
{en:"culture",ph:"/ˈkʌl.tʃər/",zh:"文化",e:"🏮",g:8,se:"I like Chinese culture.",sz:"我喜欢中国文化。"},
{en:"tradition",ph:"/trəˈdɪʃ.ən/",zh:"传统",e:"🏮",g:8,se:"It is a Chinese tradition.",sz:"这是中国的传统。"},
{en:"history",ph:"/ˈhɪs.tər.i/",zh:"历史",e:"🏛️",g:8,se:"History is interesting.",sz:"历史很有趣。"},
{en:"geography",ph:"/dʒiˈɒɡ.rə.fi/",zh:"地理",e:"🗺️",g:8,se:"We study geography.",sz:"我们学习地理。"},
{en:"biology",ph:"/baɪˈɒl.ə.dʒi/",zh:"生物",e:"🧬",g:8,se:"Biology is about life.",sz:"生物学研究生命。"},
{en:"physics",ph:"/ˈfɪz.ɪks/",zh:"物理",e:"⚛️",g:8,se:"Physics is hard.",sz:"物理很难。"},
{en:"chemistry",ph:"/ˈkem.ɪ.stri/",zh:"化学",e:"🧪",g:8,se:"We learn chemistry.",sz:"我们学化学。"},
{en:"exam",ph:"/ɪɡˈzæm/",zh:"考试",e:"📝",g:8,se:"The exam is coming.",sz:"考试要来了。"},
{en:"grade",ph:"/ɡreɪd/",zh:"成绩",e:"🎓",g:8,se:"I got a good grade.",sz:"我取得了好成绩。"},
{en:"score",ph:"/skɔː/",zh:"分数",e:"🎯",g:8,se:"My score is high.",sz:"我的分数很高。"},
{en:"memory",ph:"/ˈmem.ər.i/",zh:"记忆",e:"🧠",g:8,se:"I have a good memory.",sz:"我的记忆力很好。"},
{en:"improve",ph:"/ɪmˈpruːv/",zh:"提高",e:"📈",g:8,se:"I want to improve my English.",sz:"我想提高英语。"},
{en:"develop",ph:"/dɪˈvel.əp/",zh:"发展",e:"🌱",g:8,se:"Reading develops the mind.",sz:"阅读发展思维。"},
{en:"achieve",ph:"/əˈtʃiːv/",zh:"实现",e:"🏆",g:8,se:"You can achieve your dream.",sz:"你能实现梦想。"},
{en:"celebrate",ph:"/ˈsel.ə.breɪt/",zh:"庆祝",e:"🎉",g:8,se:"We celebrate the festival.",sz:"我们庆祝节日。"},
{en:"protect",ph:"/prəˈtekt/",zh:"保护",e:"🛡️",g:8,se:"Protect the environment.",sz:"保护环境。"},
{en:"recycle",ph:"/ˌriːˈsaɪ.kəl/",zh:"回收",e:"♻️",g:8,se:"We recycle paper.",sz:"我们回收纸张。"},
{en:"environment",ph:"/ɪnˈvaɪ.rən.mənt/",zh:"环境",e:"🌍",g:8,se:"We love our environment.",sz:"我们热爱环境。"},
{en:"pollution",ph:"/pəˈluː.ʃən/",zh:"污染",e:"☣️",g:8,se:"Air pollution is bad.",sz:"空气污染不好。"},
{en:"energy",ph:"/ˈen.ə.dʒi/",zh:"能源",e:"⚡",g:8,se:"Save energy.",sz:"节约能源。"},
{en:"technology",ph:"/tekˈnɒl.ə.dʒi/",zh:"科技",e:"💻",g:8,se:"Technology changes our life.",sz:"科技改变我们的生活。"},
{en:"machine",ph:"/məˈʃiːn/",zh:"机器",e:"🤖",g:8,se:"The machine works.",sz:"机器在工作。"},
{en:"internet",ph:"/ˈɪn.tə.net/",zh:"互联网",e:"🌐",g:8,se:"I search on the internet.",sz:"我在网上搜索。"},
{en:"message",ph:"/ˈmes.ɪdʒ/",zh:"信息",e:"💬",g:8,se:"Send me a message.",sz:"给我发条信息。"},
{en:"website",ph:"/ˈweb.saɪt/",zh:"网站",e:"🌐",g:8,se:"This website is useful.",sz:"这个网站很有用。"},
{en:"novel",ph:"/ˈnɒv.əl/",zh:"小说",e:"📖",g:8,se:"I read a novel.",sz:"我读一本小说。"},
{en:"magazine",ph:"/ˌmæɡ.əˈziːn/",zh:"杂志",e:"📓",g:8,se:"This magazine is new.",sz:"这本杂志是新的。"},
{en:"newspaper",ph:"/ˈnjuːz.peɪ.pər/",zh:"报纸",e:"📰",g:8,se:"Dad reads the newspaper.",sz:"爸爸看报纸。"},
{en:"report",ph:"/rɪˈpɔːt/",zh:"报告",e:"📊",g:8,se:"I write a report.",sz:"我写一份报告。"},
{en:"project",ph:"/ˈprɒdʒ.ekt/",zh:"项目",e:"📁",g:8,se:"Our project is about animals.",sz:"我们的项目是关于动物的。"},
/* ---- 初三（梦想·成功·能力·责任）---- */
{en:"advice",ph:"/ədˈvaɪs/",zh:"建议",e:"💡",g:9,se:"Thank you for your advice.",sz:"谢谢你的建议。"},
{en:"suggest",ph:"/səˈdʒest/",zh:"建议",e:"💬",g:9,se:"I suggest you go early.",sz:"我建议你早点去。"},
{en:"experience",ph:"/ɪkˈspɪə.ri.əns/",zh:"经历",e:"🧳",g:9,se:"It was a good experience.",sz:"那是一次好经历。"},
{en:"opportunity",ph:"/ˌɒp.əˈtjuː.nə.ti/",zh:"机会",e:"🚪",g:9,se:"This is a good opportunity.",sz:"这是个好机会。"},
{en:"challenge",ph:"/ˈtʃæl.ɪndʒ/",zh:"挑战",e:"🏔️",g:9,se:"The exam is a challenge.",sz:"考试是个挑战。"},
{en:"decision",ph:"/dɪˈsɪʒ.ən/",zh:"决定",e:"🎯",g:9,se:"Make a good decision.",sz:"做出好决定。"},
{en:"education",ph:"/ˌed.juˈkeɪ.ʃən/",zh:"教育",e:"🎓",g:9,se:"Education is important.",sz:"教育很重要。"},
{en:"society",ph:"/səˈsaɪ.ə.ti/",zh:"社会",e:"🌆",g:9,se:"We live in society.",sz:"我们生活在社会中。"},
{en:"community",ph:"/kəˈmjuː.nə.ti/",zh:"社区",e:"🏘️",g:9,se:"Our community is nice.",sz:"我们的社区很好。"},
{en:"volunteer",ph:"/ˌvɒl.ənˈtɪər/",zh:"志愿者",e:"💪",g:9,se:"I am a volunteer.",sz:"我是一名志愿者。"},
{en:"graduate",ph:"/ˈɡrædʒ.u.eɪt/",zh:"毕业",e:"🎓",g:9,se:"I will graduate next year.",sz:"我明年毕业。"},
{en:"prepare",ph:"/prɪˈpeər/",zh:"准备",e:"📦",g:9,se:"I prepare for the exam.",sz:"我为考试做准备。"},
{en:"review",ph:"/rɪˈvjuː/",zh:"复习",e:"📖",g:9,se:"I review my lessons.",sz:"我复习功课。"},
{en:"progress",ph:"/ˈprəʊ.ɡres/",zh:"进步",e:"📈",g:9,se:"I make progress every day.",sz:"我每天都在进步。"},
{en:"success",ph:"/səkˈses/",zh:"成功",e:"🏆",g:9,se:"Hard work brings success.",sz:"努力带来成功。"},
{en:"failure",ph:"/ˈfeɪ.ljər/",zh:"失败",e:"💔",g:9,se:"Failure is the mother of success.",sz:"失败是成功之母。"},
{en:"courage",ph:"/ˈkʌr.ɪdʒ/",zh:"勇气",e:"🦁",g:9,se:"I have courage.",sz:"我有勇气。"},
{en:"confidence",ph:"/ˈkɒn.fɪ.dəns/",zh:"信心",e:"💪",g:9,se:"I have confidence in myself.",sz:"我对自己有信心。"},
{en:"dream",ph:"/driːm/",zh:"梦想",e:"🌟",g:9,se:"I have a dream.",sz:"我有一个梦想。"},
{en:"future",ph:"/ˈfjuː.tʃər/",zh:"未来",e:"🔮",g:9,se:"The future is bright.",sz:"未来是光明的。"},
{en:"goal",ph:"/ɡəʊl/",zh:"目标",e:"🎯",g:9,se:"Set a goal.",sz:"定一个目标。"},
{en:"hope",ph:"/həʊp/",zh:"希望",e:"🌈",g:9,se:"I hope to see you.",sz:"我希望见到你。"},
{en:"wish",ph:"/wɪʃ/",zh:"愿望",e:"✨",g:9,se:"Make a wish.",sz:"许个愿。"},
{en:"believe",ph:"/bɪˈliːv/",zh:"相信",e:"🙏",g:9,se:"I believe in you.",sz:"我相信你。"},
{en:"trust",ph:"/trʌst/",zh:"信任",e:"🤝",g:9,se:"I trust my friend.",sz:"我信任我的朋友。"},
{en:"respect",ph:"/rɪˈspekt/",zh:"尊重",e:"🙇",g:9,se:"Respect your parents.",sz:"尊重你的父母。"},
{en:"responsibility",ph:"/rɪˌspɒn.səˈbɪl.ə.ti/",zh:"责任",e:"🎗️",g:9,se:"We have responsibility.",sz:"我们有责任。"},
{en:"duty",ph:"/ˈdjuː.ti/",zh:"义务",e:"🛡️",g:9,se:"It is my duty.",sz:"这是我的义务。"},
{en:"task",ph:"/tɑːsk/",zh:"任务",e:"📋",g:9,se:"Finish the task.",sz:"完成任务。"},
{en:"research",ph:"/rɪˈsɜːtʃ/",zh:"研究",e:"🔬",g:9,se:"I do some research.",sz:"我做一些研究。"},
{en:"experiment",ph:"/ɪkˈsper.ɪ.mənt/",zh:"实验",e:"🧪",g:9,se:"We do an experiment.",sz:"我们做实验。"},
{en:"evidence",ph:"/ˈev.ɪ.dəns/",zh:"证据",e:"🔍",g:9,se:"We need evidence.",sz:"我们需要证据。"},
{en:"conclusion",ph:"/kənˈkluː.ʒən/",zh:"结论",e:"📝",g:9,se:"What is your conclusion?",sz:"你的结论是什么？"},
{en:"solution",ph:"/səˈluː.ʃən/",zh:"解决办法",e:"🛠️",g:9,se:"Find a solution.",sz:"找到解决办法。"},
{en:"difficulty",ph:"/ˈdɪf.ɪ.kəl.ti/",zh:"困难",e:"🪨",g:9,se:"Don't give up in difficulty.",sz:"遇到困难不要放弃。"},
{en:"condition",ph:"/kənˈdɪʃ.ən/",zh:"条件",e:"📊",g:9,se:"The condition is good.",sz:"条件很好。"},
{en:"situation",ph:"/ˌsɪtʃ.uˈeɪ.ʃən/",zh:"情况",e:"📈",g:9,se:"The situation is serious.",sz:"情况很严重。"},
{en:"ability",ph:"/əˈbɪl.ə.ti/",zh:"能力",e:"💡",g:9,se:"I have the ability to do it.",sz:"我有能力做这件事。"},
{en:"skill",ph:"/skɪl/",zh:"技能",e:"🛠️",g:9,se:"Practice makes skills better.",sz:"练习让技能更好。"},
{en:"knowledge",ph:"/ˈnɒl.ɪdʒ/",zh:"知识",e:"📚",g:9,se:"Knowledge is power.",sz:"知识就是力量。"},
{en:"information",ph:"/ˌɪn.fəˈmeɪ.ʃən/",zh:"信息",e:"ℹ️",g:9,se:"The information is new.",sz:"这个信息是新的。"},
{en:"international",ph:"/ˌɪn.təˈnæʃ.ən.əl/",zh:"国际的",e:"🌐",g:9,se:"It is an international school.",sz:"这是一所国际学校。"},
{en:"global",ph:"/ˈɡləʊ.bəl/",zh:"全球的",e:"🌍",g:9,se:"It is a global problem.",sz:"这是全球性问题。"},
{en:"local",ph:"/ˈləʊ.kəl/",zh:"当地的",e:"🏠",g:9,se:"I buy local food.",sz:"我买当地的食物。"},
{en:"foreign",ph:"/ˈfɒr.ən/",zh:"外国的",e:"🗺️",g:9,se:"I learn a foreign language.",sz:"我学一门外语。"},
{en:"modern",ph:"/ˈmɒd.ən/",zh:"现代的",e:"🏙️",g:9,se:"This is a modern city.",sz:"这是一座现代城市。"},
{en:"convenient",ph:"/kənˈviː.ni.ənt/",zh:"方便的",e:"👍",g:9,se:"The bus is convenient.",sz:"公交车很方便。"},
{en:"comfortable",ph:"/ˈkʌm.fə.tə.bəl/",zh:"舒适的",e:"🛋️",g:9,se:"The bed is comfortable.",sz:"床很舒适。"}
];

/* ============ 常用短句（1-6 年级小学必会）============ */
var EN_PHRASES = [
/* ---- 一年级：问候与自我介绍 ---- */
{en:"Hello!",zh:"你好！",g:1},
{en:"Good morning!",zh:"早上好！",g:1},
{en:"Good afternoon!",zh:"下午好！",g:1},
{en:"Good evening!",zh:"晚上好！",g:1},
{en:"Good night!",zh:"晚安！",g:1},
{en:"Hi! How are you?",zh:"嗨！你好吗？",g:1},
{en:"I'm fine, thank you.",zh:"我很好，谢谢。",g:1},
{en:"What's your name?",zh:"你叫什么名字？",g:1},
{en:"My name is Tom.",zh:"我叫汤姆。",g:1},
{en:"Nice to meet you.",zh:"很高兴认识你。",g:1},
{en:"Goodbye!",zh:"再见！",g:1},
{en:"See you!",zh:"回头见！",g:1},
{en:"I'm a student.",zh:"我是一名学生。",g:1},
{en:"I'm seven years old.",zh:"我七岁了。",g:1},
{en:"How old are you?",zh:"你几岁了？",g:1},
{en:"Thank you very much.",zh:"非常感谢你。",g:1},
{en:"You're welcome.",zh:"不客气。",g:1},
{en:"I'm sorry.",zh:"对不起。",g:1},
{en:"I like apples.",zh:"我喜欢苹果。",g:1},
{en:"I like red.",zh:"我喜欢红色。",g:1},
/* ---- 二年级：课堂指令与简单描述 ---- */
{en:"Stand up, please.",zh:"请起立。",g:2},
{en:"Sit down, please.",zh:"请坐下。",g:2},
{en:"Open your book.",zh:"打开你的书。",g:2},
{en:"Close the door.",zh:"关上门。",g:2},
{en:"Look at me.",zh:"看着我。",g:2},
{en:"Listen to me.",zh:"听我说。",g:2},
{en:"Please open the window.",zh:"请打开窗户。",g:2},
{en:"This is my bag.",zh:"这是我的书包。",g:2},
{en:"That is a book.",zh:"那是一本书。",g:2},
{en:"What is this?",zh:"这是什么？",g:2},
{en:"It is a cat.",zh:"这是一只猫。",g:2},
{en:"The book is red.",zh:"这本书是红色的。",g:2},
{en:"I have a red apple.",zh:"我有一个红苹果。",g:2},
{en:"She has a blue bag.",zh:"她有一个蓝书包。",g:2},
{en:"I don't like bananas.",zh:"我不喜欢香蕉。",g:2},
{en:"Do you like apples?",zh:"你喜欢苹果吗？",g:2},
{en:"Yes, I do.",zh:"是的，我喜欢。",g:2},
{en:"No, I don't.",zh:"不，我不喜欢。",g:2},
{en:"I love my family.",zh:"我爱我的家人。",g:2},
{en:"Happy birthday to you.",zh:"祝你生日快乐。",g:2},
/* ---- 三年级：学校生活与时间 ---- */
{en:"What time is it?",zh:"现在几点了？",g:3},
{en:"It's eight o'clock.",zh:"现在八点。",g:3},
{en:"I get up at seven.",zh:"我七点起床。",g:3},
{en:"I go to school at eight.",zh:"我八点上学。",g:3},
{en:"I go to school by bus.",zh:"我坐公交车上学。",g:3},
{en:"I can swim.",zh:"我会游泳。",g:3},
{en:"I can sing a song.",zh:"我会唱一首歌。",g:3},
{en:"Can you help me?",zh:"你能帮我吗？",g:3},
{en:"Let's play together.",zh:"我们一起玩吧。",g:3},
{en:"Let's go home.",zh:"我们回家吧。",g:3},
{en:"Where is my bag?",zh:"我的书包在哪？",g:3},
{en:"It's on the desk.",zh:"它在书桌上。",g:3},
{en:"The cat is under the table.",zh:"猫在桌子下面。",g:3},
{en:"I like the blue dress.",zh:"我喜欢这条蓝裙子。",g:3},
{en:"What color do you like?",zh:"你喜欢什么颜色？",g:3},
{en:"My favorite color is blue.",zh:"我最喜欢的颜色是蓝色。",g:3},
{en:"It's a sunny day.",zh:"今天是晴天。",g:3},
{en:"It's raining now.",zh:"现在正在下雨。",g:3},
{en:"I want some milk.",zh:"我想喝点牛奶。",g:3},
{en:"May I have some water?",zh:"我可以喝点水吗？",g:3},
/* ---- 四年级：人物描述与活动 ---- */
{en:"He is my friend.",zh:"他是我的朋友。",g:4},
{en:"She is a good girl.",zh:"她是个好女孩。",g:4},
{en:"We are good friends.",zh:"我们是好朋友。",g:4},
{en:"This is my classroom.",zh:"这是我的教室。",g:4},
{en:"Our school is big.",zh:"我们的学校很大。",g:4},
{en:"I have a new bike.",zh:"我有一辆新自行车。",g:4},
{en:"My father is a doctor.",zh:"我爸爸是医生。",g:4},
{en:"Where are you going?",zh:"你要去哪里？",g:4},
{en:"I'm going to the park.",zh:"我要去公园。",g:4},
{en:"How many books do you have?",zh:"你有多少本书？",g:4},
{en:"I have three pencils.",zh:"我有三支铅笔。",g:4},
{en:"There is a book on the desk.",zh:"书桌上有一本书。",g:4},
{en:"There are five birds.",zh:"有五只鸟。",g:4},
{en:"What day is it today?",zh:"今天星期几？",g:4},
{en:"It's Monday.",zh:"今天是星期一。",g:4},
{en:"What's the weather like?",zh:"天气怎么样？",g:4},
{en:"It's warm today.",zh:"今天很暖和。",g:4},
{en:"I like spring.",zh:"我喜欢春天。",g:4},
{en:"Let's play football.",zh:"我们踢足球吧。",g:4},
{en:"I play basketball after school.",zh:"放学后我打篮球。",g:4},
/* ---- 五年级：爱好与喜好 ---- */
{en:"What's your hobby?",zh:"你的爱好是什么？",g:5},
{en:"I like reading books.",zh:"我喜欢读书。",g:5},
{en:"My hobby is drawing.",zh:"我的爱好是画画。",g:5},
{en:"What do you do on weekends?",zh:"你周末做什么？",g:5},
{en:"I often play football.",zh:"我经常踢足球。",g:5},
{en:"I sometimes watch TV.",zh:"我有时看电视。",g:5},
{en:"I usually do my homework.",zh:"我通常做作业。",g:5},
{en:"Can you dance?",zh:"你会跳舞吗？",g:5},
{en:"Yes, I can.",zh:"是的，我会。",g:5},
{en:"I'm good at swimming.",zh:"我擅长游泳。",g:5},
{en:"Which season do you like best?",zh:"你最喜欢哪个季节？",g:5},
{en:"I like summer best.",zh:"我最喜欢夏天。",g:5},
{en:"Why? Because I can swim.",zh:"为什么？因为我可以游泳。",g:5},
{en:"The elephant is bigger than the dog.",zh:"大象比狗大。",g:5},
{en:"My bag is heavier than yours.",zh:"我的书包比你的重。",g:5},
{en:"I'm taller than before.",zh:"我比以前高了。",g:5},
{en:"What would you like?",zh:"你想要什么？",g:5},
{en:"I'd like some noodles.",zh:"我想要一些面条。",g:5},
{en:"How much is it?",zh:"它多少钱？",g:5},
{en:"It's ten yuan.",zh:"十块钱。",g:5},
/* ---- 六年级：旅行、计划与过去式 ---- */
{en:"Where did you go?",zh:"你去哪里了？",g:6},
{en:"I went to Beijing.",zh:"我去了北京。",g:6},
{en:"How did you go there?",zh:"你怎么去的？",g:6},
{en:"I went by train.",zh:"我坐火车去的。",g:6},
{en:"What did you do?",zh:"你做了什么？",g:6},
{en:"I visited the Great Wall.",zh:"我参观了长城。",g:6},
{en:"Did you have a good time?",zh:"你玩得开心吗？",g:6},
{en:"Yes, I had a lot of fun.",zh:"是的，我玩得很开心。",g:6},
{en:"What are you going to do?",zh:"你打算做什么？",g:6},
{en:"I'm going to visit my grandma.",zh:"我打算去看奶奶。",g:6},
{en:"I'm going to buy some gifts.",zh:"我打算买些礼物。",g:6},
{en:"When is your birthday?",zh:"你的生日是什么时候？",g:6},
{en:"My birthday is in May.",zh:"我的生日在五月。",g:6},
{en:"Merry Christmas!",zh:"圣诞快乐！",g:6},
{en:"Happy New Year!",zh:"新年快乐！",g:6},
{en:"I have a headache.",zh:"我头疼。",g:6},
{en:"You should drink more water.",zh:"你应该多喝水。",g:6},
{en:"Keep healthy.",zh:"保持健康。",g:6},
{en:"I'm excited about the trip.",zh:"我对这次旅行很兴奋。",g:6},
{en:"See you tomorrow.",zh:"明天见。",g:6}
];

/* ============ 自然拼读（音标+例词音标）============ */
var EN_PHONICS = [
{g:"a（短音）",s:"/æ/",sp:"像 cat 里的 a",ex:[{w:"cat",ph:"/kæt/"},{w:"map",ph:"/mæp/"},{w:"hat",ph:"/hæt/"},{w:"bat",ph:"/bæt/"}]},
{g:"a_e（长音）",s:"/eɪ/",sp:"像 cake 里的 a",ex:[{w:"cake",ph:"/keɪk/"},{w:"name",ph:"/neɪm/"},{w:"face",ph:"/feɪs/"},{w:"lake",ph:"/leɪk/"}]},
{g:"e（短音）",s:"/e/",sp:"像 bed 里的 e",ex:[{w:"bed",ph:"/bed/"},{w:"pen",ph:"/pen/"},{w:"red",ph:"/red/"},{w:"leg",ph:"/leɡ/"}]},
{g:"i（短音）",s:"/ɪ/",sp:"像 pig 里的 i",ex:[{w:"pig",ph:"/pɪɡ/"},{w:"sit",ph:"/sɪt/"},{w:"big",ph:"/bɪɡ/"},{w:"lip",ph:"/lɪp/"}]},
{g:"i_e（长音）",s:"/aɪ/",sp:"像 bike 里的 i",ex:[{w:"bike",ph:"/baɪk/"},{w:"kite",ph:"/kaɪt/"},{w:"time",ph:"/taɪm/"},{w:"ride",ph:"/raɪd/"}]},
{g:"o（短音）",s:"/ɒ/",sp:"像 dog 里的 o",ex:[{w:"dog",ph:"/dɒɡ/"},{w:"hot",ph:"/hɒt/"},{w:"box",ph:"/bɒks/"},{w:"pot",ph:"/pɒt/"}]},
{g:"o_e（长音）",s:"/əʊ/",sp:"像 nose 里的 o",ex:[{w:"nose",ph:"/nəʊz/"},{w:"rope",ph:"/rəʊp/"},{w:"note",ph:"/nəʊt/"},{w:"home",ph:"/həʊm/"}]},
{g:"u（短音）",s:"/ʌ/",sp:"像 cup 里的 u",ex:[{w:"cup",ph:"/kʌp/"},{w:"sun",ph:"/sʌn/"},{w:"bus",ph:"/bʌs/"},{w:"run",ph:"/rʌn/"}]},
{g:"u_e（长音）",s:"/juː/",sp:"像 cute 里的 u",ex:[{w:"cute",ph:"/kjuːt/"},{w:"tube",ph:"/tjuːb/"},{w:"mule",ph:"/mjuːl/"},{w:"rule",ph:"/ruːl/"}]},
{g:"sh",s:"/ʃ/",sp:"像 ship 里的 sh",ex:[{w:"ship",ph:"/ʃɪp/"},{w:"fish",ph:"/fɪʃ/"},{w:"shoe",ph:"/ʃuː/"},{w:"dish",ph:"/dɪʃ/"}]},
{g:"ch",s:"/tʃ/",sp:"像 chair 里的 ch",ex:[{w:"chair",ph:"/tʃeər/"},{w:"chick",ph:"/tʃɪk/"},{w:"cheese",ph:"/tʃiːz/"},{w:"much",ph:"/mʌtʃ/"}]},
{g:"th（清音）",s:"/θ/",sp:"像 three 里的 th",ex:[{w:"three",ph:"/θriː/"},{w:"thumb",ph:"/θʌm/"},{w:"thick",ph:"/θɪk/"},{w:"math",ph:"/mæθ/"}]},
{g:"th（浊音）",s:"/ð/",sp:"像 this 里的 th",ex:[{w:"this",ph:"/ðɪs/"},{w:"that",ph:"/ðæt/"},{w:"mother",ph:"/ˈmʌð.ər/"},{w:"father",ph:"/ˈfɑː.ðər/"}]},
{g:"ck",s:"/k/",sp:"像 duck 里的 ck",ex:[{w:"duck",ph:"/dʌk/"},{w:"lock",ph:"/lɒk/"},{w:"back",ph:"/bæk/"},{w:"sock",ph:"/sɒk/"}]},
{g:"ng",s:"/ŋ/",sp:"像 sing 里的 ng",ex:[{w:"ring",ph:"/rɪŋ/"},{w:"song",ph:"/sɒŋ/"},{w:"king",ph:"/kɪŋ/"},{w:"sing",ph:"/sɪŋ/"}]},
{g:"ee",s:"/iː/",sp:"像 bee 里的 ee",ex:[{w:"bee",ph:"/biː/"},{w:"see",ph:"/siː/"},{w:"tree",ph:"/triː/"},{w:"green",ph:"/ɡriːn/"}]},
{g:"oa",s:"/əʊ/",sp:"像 boat 里的 oa",ex:[{w:"boat",ph:"/bəʊt/"},{w:"coat",ph:"/kəʊt/"},{w:"road",ph:"/rəʊd/"},{w:"goat",ph:"/ɡəʊt/"}]},
{g:"ai",s:"/eɪ/",sp:"像 rain 里的 ai",ex:[{w:"rain",ph:"/reɪn/"},{w:"mail",ph:"/meɪl/"},{w:"tail",ph:"/teɪl/"},{w:"train",ph:"/treɪn/"}]},
{g:"oo（长音）",s:"/uː/",sp:"像 moon 里的 oo",ex:[{w:"moon",ph:"/muːn/"},{w:"food",ph:"/fuːd/"},{w:"room",ph:"/ruːm/"},{w:"zoo",ph:"/zuː/"}]},
{g:"oo（短音）",s:"/ʊ/",sp:"像 book 里的 oo",ex:[{w:"book",ph:"/bʊk/"},{w:"look",ph:"/lʊk/"},{w:"foot",ph:"/fʊt/"},{w:"good",ph:"/ɡʊd/"}]},
{g:"ar",s:"/ɑː/",sp:"像 car 里的 ar",ex:[{w:"car",ph:"/kɑː/"},{w:"star",ph:"/stɑː/"},{w:"arm",ph:"/ɑːm/"},{w:"park",ph:"/pɑːk/"}]},
{g:"or",s:"/ɔː/",sp:"像 horse 里的 or",ex:[{w:"horse",ph:"/hɔːs/"},{w:"short",ph:"/ʃɔːt/"},{w:"for",ph:"/fɔːr/"},{w:"morning",ph:"/ˈmɔː.nɪŋ/"}]},
{g:"er",s:"/ɜː/",sp:"像 her 里的 er",ex:[{w:"her",ph:"/hɜːr/"},{w:"teacher",ph:"/ˈtiː.tʃər/"},{w:"sister",ph:"/ˈsɪs.tər/"},{w:"water",ph:"/ˈwɔː.tər/"}]},
{g:"ou",s:"/aʊ/",sp:"像 mouth 里的 ou",ex:[{w:"mouth",ph:"/maʊθ/"},{w:"house",ph:"/haʊs/"},{w:"mouse",ph:"/maʊs/"},{w:"sound",ph:"/saʊnd/"}]},
{g:"ow",s:"/aʊ/",sp:"像 cow 里的 ow",ex:[{w:"cow",ph:"/kaʊ/"},{w:"how",ph:"/haʊ/"},{w:"now",ph:"/naʊ/"},{w:"brown",ph:"/braʊn/"}]},
{g:"oi",s:"/ɔɪ/",sp:"像 boy 里的 oy",ex:[{w:"coin",ph:"/kɔɪn/"},{w:"boy",ph:"/bɔɪ/"},{w:"toy",ph:"/tɔɪ/"},{w:"noise",ph:"/nɔɪz/"}]},
{g:"qu",s:"/kw/",sp:"像 queen 里的 qu",ex:[{w:"queen",ph:"/kwiːn/"},{w:"quiet",ph:"/ˈkwaɪ.ət/"},{w:"quick",ph:"/kwɪk/"},{w:"question",ph:"/ˈkwes.tʃən/"}]},
{g:"igh",s:"/aɪ/",sp:"像 light 里的 igh",ex:[{w:"light",ph:"/laɪt/"},{w:"night",ph:"/naɪt/"},{w:"right",ph:"/raɪt/"},{w:"high",ph:"/haɪ/"}]}
];
